/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Chunk */
        get: operations["v1_chunk_api_v1_chunks__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Facets */
        get: operations["v1_facets_api_v1_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Graph */
        get: operations["v1_graph_api_v1_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Renderer Graph */
        get: operations["v1_renderer_graph_api_v1_graph_projection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Runtime */
        get: operations["v1_runtime_api_v1_runtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Search */
        get: operations["v1_search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Trail */
        get: operations["v1_trail_api_v1_trail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worktrees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Worktrees */
        get: operations["v1_worktrees_api_v1_worktrees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthorityClass
         * @description What authority an item's *meaning* carries — a separate axis from
         *     ``ProvenanceClass`` (where it came from). Fixed vocabulary from the
         *     provenance/authority taxonomy (BG1) so generated or provider-derived content
         *     can never masquerade as authored project memory.
         *
         *     Confidence is separate metadata and can never upgrade authority.
         * @enum {string}
         */
        AuthorityClass: "authored" | "computed_canonical" | "git_derived" | "provider_extracted" | "provider_resolved" | "provider_inferred" | "generated";
        /**
         * BranchInfo
         * @description Per-branch Trail geometry recovered from trailer ground truth: the merge
         *     event that closed the branch's newest displayed entry (``merge`` is None when
         *     that newest entry is still open - the branch dangles, no fabricated merge),
         *     the fork point, and ``estimated`` (True only in the pre-trailer era, where the
         *     frontend keeps its positional heuristic).
         */
        BranchInfo: {
            /** Estimated */
            estimated: boolean;
            fork: components["schemas"]["ForkPoint"] | null;
            merge: components["schemas"]["CommitInfo"] | null;
        };
        /**
         * ChunkBrief
         * @description The compact shape used for commit_entries/suggestions (_chunk_summary).
         */
        ChunkBrief: {
            /** Agent */
            agent: string;
            /** Chunk Id */
            chunk_id: string;
            /** Date */
            date: string;
            /** Entry Id */
            entry_id: string | null;
            /** Time */
            time: string | null;
            /** Title */
            title: string;
            /** Topics */
            topics: string[];
        };
        /** ChunkMetadata */
        ChunkMetadata: {
            /** Agent Name */
            agent_name: string | null;
            /** Agent Type */
            agent_type: string | null;
            /** File Hash Id */
            file_hash_id: string | null;
            /** Granularity */
            granularity: string;
            /** Project Path */
            project_path: string | null;
            /** Source */
            source: string | null;
            /** Subproject Path */
            subproject_path: string | null;
            /** User */
            user: string | null;
        };
        /** ChunkResponse */
        ChunkResponse: {
            /** Agent Name */
            agent_name: string | null;
            /** Agent Type */
            agent_type: string | null;
            /** Backlinks */
            backlinks: string[];
            /** Branch */
            branch: string | null;
            /** Chunk Id */
            chunk_id: string;
            commit: components["schemas"]["CommitInfo"] | null;
            /** Commit Entries */
            commit_entries: components["schemas"]["ChunkBrief"][];
            /** Commit Entry Ids */
            commit_entry_ids: string[];
            /** Commit Tracking */
            commit_tracking: boolean;
            /** Contexts */
            contexts: string[];
            /** Continuity */
            continuity: components["schemas"]["ContinuityItem"][];
            /** Date */
            date: string;
            /** Diagrams */
            diagrams: {
                [key: string]: unknown;
            }[];
            /** Entry Datetime */
            entry_datetime: string | null;
            /** Entry Id */
            entry_id: string | null;
            /** Entry Title */
            entry_title: string | null;
            /** Excerpt */
            excerpt: string;
            /** Granularity */
            granularity: string;
            /** Heading Path */
            heading_path: string[];
            /** Lexical Terms */
            lexical_terms: string[];
            /** Line Range */
            line_range: number[];
            merged_by: components["schemas"]["CommitInfo"] | null;
            metadata: components["schemas"]["ChunkMetadata"];
            /** Path */
            path: string | null;
            /** Related Entries */
            related_entries: string[];
            /** Sections */
            sections: string[];
            /** Source */
            source: string | null;
            suggestions: components["schemas"]["Suggestions"];
            /** Tags */
            tags: string[];
            /** Text */
            text: string;
            /** Time */
            time: string | null;
            /** Title */
            title: string;
            /** Topics */
            topics: string[];
            /** User */
            user: string | null;
        };
        /** CommitInfo */
        CommitInfo: {
            /** Date */
            date: string;
            /** Sha */
            sha: string;
            /** Short */
            short: string;
            /** Subject */
            subject: string;
        };
        /**
         * ContinuityItem
         * @description One authored continuity block exposed through Trace read contracts.
         */
        ContinuityItem: {
            /** From */
            from: string;
            /** Kind */
            kind: string;
            /** To */
            to?: string | null;
        };
        /**
         * EdgeType
         * @description Every edge kind _graph_edges() can produce (graph-edge-contract.md).
         * @enum {string}
         */
        EdgeType: "related" | "supersedes" | "evolves" | "branch" | "topic" | "agent" | "day";
        /** Facets */
        Facets: {
            /** Agents */
            agents: {
                [key: string]: number;
            };
            runtime: components["schemas"]["FacetsRuntimeInfo"];
            /** Topics */
            topics: {
                [key: string]: number;
            };
            /** Users */
            users: {
                [key: string]: number;
            };
        };
        /** FacetsRuntimeInfo */
        FacetsRuntimeInfo: {
            /** Cache Path */
            cache_path: string;
            /** Chunk Count */
            chunk_count: number;
            /** Date Bounds */
            date_bounds: (string | null)[];
            /** Entry Count */
            entry_count: number;
            /** Label */
            label: string;
            /** Legacy */
            legacy: boolean;
            /** Memory Dir */
            memory_dir: string;
            /** Workspace Root */
            workspace_root: string;
        };
        /**
         * ForkPoint
         * @description Where a merged branch left the trunk: the merge-base of the merge
         *     commit's parents. No ``subject`` - a fork point is a plain trunk commit,
         *     not itself a merge.
         */
        ForkPoint: {
            /** Date */
            date: string;
            /** Sha */
            sha: string;
            /** Short */
            short: string;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            type: components["schemas"]["EdgeType"];
        };
        /** GraphNode */
        GraphNode: {
            /** Agent */
            agent: string;
            /** Branch */
            branch: string | null;
            /** Branch Inferred */
            branch_inferred: boolean;
            /** Chunk Id */
            chunk_id: string;
            /** Connectivity */
            connectivity: number;
            /** Continuity */
            continuity: components["schemas"]["ContinuityItem"][];
            /** Date */
            date: string;
            /** Datetime */
            datetime: string | null;
            /**
             * Decision Count
             * @default 0
             */
            decision_count: number;
            /** Decision Ordinal */
            decision_ordinal?: string | null;
            /** Entry Id */
            entry_id: string | null;
            /** Granularity */
            granularity: string;
            /**
             * Has Diagram
             * @default false
             */
            has_diagram: boolean;
            /** Id */
            id: string;
            /** Importance Score */
            importance_score: number;
            /** @default authored_memory */
            provenance_class: components["schemas"]["ProvenanceClass"];
            /** Title */
            title: string;
            /** Topics */
            topics: string[];
        };
        /** GraphResponse */
        GraphResponse: {
            /** Branches */
            branches: {
                [key: string]: components["schemas"]["BranchInfo"];
            };
            /** Edge Types */
            edge_types: components["schemas"]["EdgeType"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Entry Id */
            entry_id: string | null;
            /** Granularity */
            granularity: string;
            /** Merges */
            merges: components["schemas"]["MergeEvent"][];
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MatchedSection */
        MatchedSection: {
            /** Chunk Id */
            chunk_id: string;
            /** Excerpt */
            excerpt: string;
            /** Heading Path */
            heading_path: string[];
            /** Line Range */
            line_range: number[];
        };
        /**
         * MergeEvent
         * @description A trunk merge commit carrying ``Memory-Entry:`` trailers - the
         *     commit-accurate join between a merge and the entries it landed on main
         *     (``session merge-branch`` stamps one trailer per merged entry). ``entry_ids``
         *     is filtered to the displayed nodes.
         */
        MergeEvent: {
            /** Date */
            date: string;
            /** Entry Ids */
            entry_ids: string[];
            /** Sha */
            sha: string;
            /** Short */
            short: string;
            /** Subject */
            subject: string;
        };
        /**
         * ProvenanceClass
         * @description Fixed enum from the Trail/Graph UX spec (SS3.2) so future event types
         *     (PR review, CI, release, ...) never masquerade as authored memory. Only
         *     ``authored_memory`` is ever emitted today.
         * @enum {string}
         */
        ProvenanceClass: "authored_memory" | "source_control" | "pr_review" | "automation_ci" | "annotation" | "release" | "generated_artefact";
        /** RendererGraphCommunity */
        RendererGraphCommunity: {
            /** Fingerprint */
            fingerprint: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** RendererGraphEdge */
        RendererGraphEdge: {
            /** Directed */
            directed: boolean;
            edge_type: components["schemas"]["EdgeType"];
            /** Evidence Refs */
            evidence_refs: string[];
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** RendererGraphNode */
        RendererGraphNode: {
            authority_class: components["schemas"]["AuthorityClass"];
            community: components["schemas"]["RendererGraphCommunity"];
            /** Connectivity */
            connectivity: number;
            /** Id */
            id: string;
            /** Importance Score */
            importance_score: number;
            /** Label */
            label: string;
            /** Node Type */
            node_type: string;
            provenance_class: components["schemas"]["ProvenanceClass"];
            /** Provider */
            provider: string | null;
            /** Revision */
            revision: string | null;
            source: components["schemas"]["RendererGraphSource"];
            /** Stale */
            stale: boolean;
            temporal: components["schemas"]["RendererGraphTemporal"];
        };
        /** RendererGraphResponse */
        RendererGraphResponse: {
            /** Edges */
            edges: components["schemas"]["RendererGraphEdge"][];
            /** Nodes */
            nodes: components["schemas"]["RendererGraphNode"][];
        };
        /** RendererGraphSource */
        RendererGraphSource: {
            /** Agent */
            agent: string;
            /** Chunk Id */
            chunk_id: string;
            /** Entry Id */
            entry_id: string | null;
            /** Topics */
            topics: string[];
        };
        /** RendererGraphTemporal */
        RendererGraphTemporal: {
            /** Precision */
            precision: string;
            /** Source */
            source: string;
            /** Value */
            value: string;
        };
        /** RuntimeInfo */
        RuntimeInfo: {
            /** Cache Path */
            cache_path: string;
            /** Date Bounds */
            date_bounds: (string | null)[];
            /** Entry Count */
            entry_count: number;
            /** Label */
            label: string;
            /** Legacy */
            legacy: boolean;
            /** Memory Dir */
            memory_dir: string;
            /** Workspace Root */
            workspace_root: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Cursor */
            cursor: string | null;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchResult"][];
            /** Total */
            total: number;
        };
        /** SearchResult */
        SearchResult: {
            /** Agent Name */
            agent_name: string | null;
            /** Agent Type */
            agent_type: string | null;
            /** Best Match Chunk Id */
            best_match_chunk_id?: string | null;
            /** Branch */
            branch: string | null;
            /** Chunk Id */
            chunk_id: string;
            /** Contexts */
            contexts: string[];
            /** Continuity */
            continuity: components["schemas"]["ContinuityItem"][];
            /** Date */
            date: string;
            /** Entry Datetime */
            entry_datetime: string | null;
            /** Entry Id */
            entry_id: string | null;
            /** Entry Title */
            entry_title: string | null;
            /** Excerpt */
            excerpt: string;
            /** Granularity */
            granularity: string;
            /** Heading Path */
            heading_path: string[];
            /** Lexical Score */
            lexical_score: number;
            /** Lexical Terms */
            lexical_terms: string[];
            /** Line Range */
            line_range: number[];
            /** Match Score */
            match_score: number;
            /** Matched Fields */
            matched_fields: string[];
            /**
             * Matched Sections
             * @default []
             */
            matched_sections: components["schemas"]["MatchedSection"][];
            /** Matched Terms */
            matched_terms: string[];
            /** Path */
            path: string | null;
            /** Recency Multiplier */
            recency_multiplier: number;
            /** Related Entries */
            related_entries: string[];
            /** Score */
            score: number;
            /** Score Explanation */
            score_explanation: string;
            /** Score Source */
            score_source?: string | null;
            /** Sections */
            sections: string[];
            /** Semantic Score */
            semantic_score: number | null;
            /** Source */
            source: string | null;
            /** Tags */
            tags: string[];
            /** Text */
            text: string;
            /** Time */
            time: string | null;
            /** Title */
            title: string;
            /** Topics */
            topics: string[];
            /** User */
            user: string | null;
        };
        /** Suggestions */
        Suggestions: {
            /** Same Agent */
            same_agent: components["schemas"]["ChunkBrief"][];
            /** Same Day */
            same_day: components["schemas"]["ChunkBrief"][];
            /** Same Topic */
            same_topic: components["schemas"]["ChunkBrief"][];
        };
        /**
         * TrailEvent
         * @description The Trail's own event contract. Structurally identical to GraphNode
         *     today (both are served by the same TraceService.graph() call, entry
         *     granularity) - named distinctly because the product UX treats Trail as
         *     the primary surface and Graph as a secondary, general-purpose one; a
         *     future divergence (e.g. Trail-only fields) should widen this model, not
         *     GraphNode.
         */
        TrailEvent: {
            /** Agent */
            agent: string;
            /** Branch */
            branch: string | null;
            /** Branch Inferred */
            branch_inferred: boolean;
            /** Chunk Id */
            chunk_id: string;
            /** Connectivity */
            connectivity: number;
            /** Continuity */
            continuity: components["schemas"]["ContinuityItem"][];
            /** Date */
            date: string;
            /** Datetime */
            datetime: string | null;
            /**
             * Decision Count
             * @default 0
             */
            decision_count: number;
            /** Decision Ordinal */
            decision_ordinal?: string | null;
            /** Entry Id */
            entry_id: string | null;
            /** Granularity */
            granularity: string;
            /**
             * Has Diagram
             * @default false
             */
            has_diagram: boolean;
            /** Id */
            id: string;
            /** Importance Score */
            importance_score: number;
            /** @default authored_memory */
            provenance_class: components["schemas"]["ProvenanceClass"];
            /** Title */
            title: string;
            /** Topics */
            topics: string[];
        };
        /** TrailResponse */
        TrailResponse: {
            /** Branches */
            branches: {
                [key: string]: components["schemas"]["BranchInfo"];
            };
            /** Edge Types */
            edge_types: components["schemas"]["EdgeType"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Entry Id */
            entry_id: string | null;
            /** Granularity */
            granularity: string;
            /** Merges */
            merges: components["schemas"]["MergeEvent"][];
            /** Nodes */
            nodes: components["schemas"]["TrailEvent"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorktreeInfo */
        WorktreeInfo: {
            /** Branch */
            branch: string | null;
            /** Id */
            id: string;
            /** Is Default */
            is_default: boolean;
            /** Is Primary */
            is_primary: boolean;
            /** Label */
            label: string;
            /** Path */
            path: string;
        };
        /** WorktreesResponse */
        WorktreesResponse: {
            /** Default */
            default: string;
            /** Worktrees */
            worktrees: components["schemas"]["WorktreeInfo"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_chunk_api_v1_chunks__chunk_id__get: {
        parameters: {
            query?: {
                worktree?: string | null;
            };
            header?: never;
            path: {
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    v1_facets_api_v1_facets_get: {
        parameters: {
            query?: {
                worktree?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    v1_graph_api_v1_graph_get: {
        parameters: {
            query?: {
                entry_id?: string | null;
                depth?: number;
                edge_types?: string;
                limit?: number;
                granularity?: string;
                agent?: string | null;
                user?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                topic?: string | null;
                worktree?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    v1_renderer_graph_api_v1_graph_projection_get: {
        parameters: {
            query?: {
                entry_id?: string | null;
                depth?: number;
                edge_types?: string;
                limit?: number;
                granularity?: string;
                agent?: string | null;
                user?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                topic?: string | null;
                path?: string | null;
                worktree?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RendererGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    v1_runtime_api_v1_runtime_get: {
        parameters: {
            query?: {
                worktree?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    v1_search_api_v1_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
                cursor?: string | null;
                granularity?: string;
                agent?: string | null;
                user?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                topic?: string | null;
                sort?: string;
                worktree?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    v1_trail_api_v1_trail_get: {
        parameters: {
            query?: {
                entry_id?: string | null;
                depth?: number;
                limit?: number;
                agent?: string | null;
                user?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                topic?: string | null;
                worktree?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    v1_worktrees_api_v1_worktrees_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorktreesResponse"];
                };
            };
        };
    };
}
